require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DevelopmentAreasController do

  # This should return the minimal set of attributes required to create a valid
  # DevelopmentArea. As you add validations to DevelopmentArea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DevelopmentAreasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all development_areas as @development_areas" do
      development_area = DevelopmentArea.create! valid_attributes
      get :index, {}, valid_session
      assigns(:development_areas).should eq([development_area])
    end
  end

  describe "GET show" do
    it "assigns the requested development_area as @development_area" do
      development_area = DevelopmentArea.create! valid_attributes
      get :show, {:id => development_area.to_param}, valid_session
      assigns(:development_area).should eq(development_area)
    end
  end

  describe "GET new" do
    it "assigns a new development_area as @development_area" do
      get :new, {}, valid_session
      assigns(:development_area).should be_a_new(DevelopmentArea)
    end
  end

  describe "GET edit" do
    it "assigns the requested development_area as @development_area" do
      development_area = DevelopmentArea.create! valid_attributes
      get :edit, {:id => development_area.to_param}, valid_session
      assigns(:development_area).should eq(development_area)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DevelopmentArea" do
        expect {
          post :create, {:development_area => valid_attributes}, valid_session
        }.to change(DevelopmentArea, :count).by(1)
      end

      it "assigns a newly created development_area as @development_area" do
        post :create, {:development_area => valid_attributes}, valid_session
        assigns(:development_area).should be_a(DevelopmentArea)
        assigns(:development_area).should be_persisted
      end

      it "redirects to the created development_area" do
        post :create, {:development_area => valid_attributes}, valid_session
        response.should redirect_to(DevelopmentArea.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved development_area as @development_area" do
        # Trigger the behavior that occurs when invalid params are submitted
        DevelopmentArea.any_instance.stub(:save).and_return(false)
        post :create, {:development_area => { "name" => "invalid value" }}, valid_session
        assigns(:development_area).should be_a_new(DevelopmentArea)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DevelopmentArea.any_instance.stub(:save).and_return(false)
        post :create, {:development_area => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested development_area" do
        development_area = DevelopmentArea.create! valid_attributes
        # Assuming there are no other development_areas in the database, this
        # specifies that the DevelopmentArea created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DevelopmentArea.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => development_area.to_param, :development_area => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested development_area as @development_area" do
        development_area = DevelopmentArea.create! valid_attributes
        put :update, {:id => development_area.to_param, :development_area => valid_attributes}, valid_session
        assigns(:development_area).should eq(development_area)
      end

      it "redirects to the development_area" do
        development_area = DevelopmentArea.create! valid_attributes
        put :update, {:id => development_area.to_param, :development_area => valid_attributes}, valid_session
        response.should redirect_to(development_area)
      end
    end

    describe "with invalid params" do
      it "assigns the development_area as @development_area" do
        development_area = DevelopmentArea.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DevelopmentArea.any_instance.stub(:save).and_return(false)
        put :update, {:id => development_area.to_param, :development_area => { "name" => "invalid value" }}, valid_session
        assigns(:development_area).should eq(development_area)
      end

      it "re-renders the 'edit' template" do
        development_area = DevelopmentArea.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DevelopmentArea.any_instance.stub(:save).and_return(false)
        put :update, {:id => development_area.to_param, :development_area => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested development_area" do
      development_area = DevelopmentArea.create! valid_attributes
      expect {
        delete :destroy, {:id => development_area.to_param}, valid_session
      }.to change(DevelopmentArea, :count).by(-1)
    end

    it "redirects to the development_areas list" do
      development_area = DevelopmentArea.create! valid_attributes
      delete :destroy, {:id => development_area.to_param}, valid_session
      response.should redirect_to(development_areas_url)
    end
  end

end
