require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MasterContractsController do

  # This should return the minimal set of attributes required to create a valid
  # MasterContract. As you add validations to MasterContract, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "contract_label" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MasterContractsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all master_contracts as @master_contracts" do
      master_contract = MasterContract.create! valid_attributes
      get :index, {}, valid_session
      assigns(:master_contracts).should eq([master_contract])
    end
  end

  describe "GET show" do
    it "assigns the requested master_contract as @master_contract" do
      master_contract = MasterContract.create! valid_attributes
      get :show, {:id => master_contract.to_param}, valid_session
      assigns(:master_contract).should eq(master_contract)
    end
  end

  describe "GET new" do
    it "assigns a new master_contract as @master_contract" do
      get :new, {}, valid_session
      assigns(:master_contract).should be_a_new(MasterContract)
    end
  end

  describe "GET edit" do
    it "assigns the requested master_contract as @master_contract" do
      master_contract = MasterContract.create! valid_attributes
      get :edit, {:id => master_contract.to_param}, valid_session
      assigns(:master_contract).should eq(master_contract)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MasterContract" do
        expect {
          post :create, {:master_contract => valid_attributes}, valid_session
        }.to change(MasterContract, :count).by(1)
      end

      it "assigns a newly created master_contract as @master_contract" do
        post :create, {:master_contract => valid_attributes}, valid_session
        assigns(:master_contract).should be_a(MasterContract)
        assigns(:master_contract).should be_persisted
      end

      it "redirects to the created master_contract" do
        post :create, {:master_contract => valid_attributes}, valid_session
        response.should redirect_to(MasterContract.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved master_contract as @master_contract" do
        # Trigger the behavior that occurs when invalid params are submitted
        MasterContract.any_instance.stub(:save).and_return(false)
        post :create, {:master_contract => { "contract_label" => "invalid value" }}, valid_session
        assigns(:master_contract).should be_a_new(MasterContract)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MasterContract.any_instance.stub(:save).and_return(false)
        post :create, {:master_contract => { "contract_label" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested master_contract" do
        master_contract = MasterContract.create! valid_attributes
        # Assuming there are no other master_contracts in the database, this
        # specifies that the MasterContract created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MasterContract.any_instance.should_receive(:update).with({ "contract_label" => "MyString" })
        put :update, {:id => master_contract.to_param, :master_contract => { "contract_label" => "MyString" }}, valid_session
      end

      it "assigns the requested master_contract as @master_contract" do
        master_contract = MasterContract.create! valid_attributes
        put :update, {:id => master_contract.to_param, :master_contract => valid_attributes}, valid_session
        assigns(:master_contract).should eq(master_contract)
      end

      it "redirects to the master_contract" do
        master_contract = MasterContract.create! valid_attributes
        put :update, {:id => master_contract.to_param, :master_contract => valid_attributes}, valid_session
        response.should redirect_to(master_contract)
      end
    end

    describe "with invalid params" do
      it "assigns the master_contract as @master_contract" do
        master_contract = MasterContract.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MasterContract.any_instance.stub(:save).and_return(false)
        put :update, {:id => master_contract.to_param, :master_contract => { "contract_label" => "invalid value" }}, valid_session
        assigns(:master_contract).should eq(master_contract)
      end

      it "re-renders the 'edit' template" do
        master_contract = MasterContract.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MasterContract.any_instance.stub(:save).and_return(false)
        put :update, {:id => master_contract.to_param, :master_contract => { "contract_label" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested master_contract" do
      master_contract = MasterContract.create! valid_attributes
      expect {
        delete :destroy, {:id => master_contract.to_param}, valid_session
      }.to change(MasterContract, :count).by(-1)
    end

    it "redirects to the master_contracts list" do
      master_contract = MasterContract.create! valid_attributes
      delete :destroy, {:id => master_contract.to_param}, valid_session
      response.should redirect_to(master_contracts_url)
    end
  end

end
