require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PropertyOwnersController do

  # This should return the minimal set of attributes required to create a valid
  # PropertyOwner. As you add validations to PropertyOwner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "company_name" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PropertyOwnersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all property_owners as @property_owners" do
      property_owner = PropertyOwner.create! valid_attributes
      get :index, {}, valid_session
      assigns(:property_owners).should eq([property_owner])
    end
  end

  describe "GET show" do
    it "assigns the requested property_owner as @property_owner" do
      property_owner = PropertyOwner.create! valid_attributes
      get :show, {:id => property_owner.to_param}, valid_session
      assigns(:property_owner).should eq(property_owner)
    end
  end

  describe "GET new" do
    it "assigns a new property_owner as @property_owner" do
      get :new, {}, valid_session
      assigns(:property_owner).should be_a_new(PropertyOwner)
    end
  end

  describe "GET edit" do
    it "assigns the requested property_owner as @property_owner" do
      property_owner = PropertyOwner.create! valid_attributes
      get :edit, {:id => property_owner.to_param}, valid_session
      assigns(:property_owner).should eq(property_owner)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PropertyOwner" do
        expect {
          post :create, {:property_owner => valid_attributes}, valid_session
        }.to change(PropertyOwner, :count).by(1)
      end

      it "assigns a newly created property_owner as @property_owner" do
        post :create, {:property_owner => valid_attributes}, valid_session
        assigns(:property_owner).should be_a(PropertyOwner)
        assigns(:property_owner).should be_persisted
      end

      it "redirects to the created property_owner" do
        post :create, {:property_owner => valid_attributes}, valid_session
        response.should redirect_to(PropertyOwner.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved property_owner as @property_owner" do
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyOwner.any_instance.stub(:save).and_return(false)
        post :create, {:property_owner => { "company_name" => "invalid value" }}, valid_session
        assigns(:property_owner).should be_a_new(PropertyOwner)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyOwner.any_instance.stub(:save).and_return(false)
        post :create, {:property_owner => { "company_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested property_owner" do
        property_owner = PropertyOwner.create! valid_attributes
        # Assuming there are no other property_owners in the database, this
        # specifies that the PropertyOwner created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PropertyOwner.any_instance.should_receive(:update).with({ "company_name" => "" })
        put :update, {:id => property_owner.to_param, :property_owner => { "company_name" => "" }}, valid_session
      end

      it "assigns the requested property_owner as @property_owner" do
        property_owner = PropertyOwner.create! valid_attributes
        put :update, {:id => property_owner.to_param, :property_owner => valid_attributes}, valid_session
        assigns(:property_owner).should eq(property_owner)
      end

      it "redirects to the property_owner" do
        property_owner = PropertyOwner.create! valid_attributes
        put :update, {:id => property_owner.to_param, :property_owner => valid_attributes}, valid_session
        response.should redirect_to(property_owner)
      end
    end

    describe "with invalid params" do
      it "assigns the property_owner as @property_owner" do
        property_owner = PropertyOwner.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyOwner.any_instance.stub(:save).and_return(false)
        put :update, {:id => property_owner.to_param, :property_owner => { "company_name" => "invalid value" }}, valid_session
        assigns(:property_owner).should eq(property_owner)
      end

      it "re-renders the 'edit' template" do
        property_owner = PropertyOwner.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyOwner.any_instance.stub(:save).and_return(false)
        put :update, {:id => property_owner.to_param, :property_owner => { "company_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested property_owner" do
      property_owner = PropertyOwner.create! valid_attributes
      expect {
        delete :destroy, {:id => property_owner.to_param}, valid_session
      }.to change(PropertyOwner, :count).by(-1)
    end

    it "redirects to the property_owners list" do
      property_owner = PropertyOwner.create! valid_attributes
      delete :destroy, {:id => property_owner.to_param}, valid_session
      response.should redirect_to(property_owners_url)
    end
  end

end
