require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UnitTemplateMergingsController do

  # This should return the minimal set of attributes required to create a valid
  # UnitTemplateMerging. As you add validations to UnitTemplateMerging, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UnitTemplateMergingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all unit_template_mergings as @unit_template_mergings" do
      unit_template_merging = UnitTemplateMerging.create! valid_attributes
      get :index, {}, valid_session
      assigns(:unit_template_mergings).should eq([unit_template_merging])
    end
  end

  describe "GET show" do
    it "assigns the requested unit_template_merging as @unit_template_merging" do
      unit_template_merging = UnitTemplateMerging.create! valid_attributes
      get :show, {:id => unit_template_merging.to_param}, valid_session
      assigns(:unit_template_merging).should eq(unit_template_merging)
    end
  end

  describe "GET new" do
    it "assigns a new unit_template_merging as @unit_template_merging" do
      get :new, {}, valid_session
      assigns(:unit_template_merging).should be_a_new(UnitTemplateMerging)
    end
  end

  describe "GET edit" do
    it "assigns the requested unit_template_merging as @unit_template_merging" do
      unit_template_merging = UnitTemplateMerging.create! valid_attributes
      get :edit, {:id => unit_template_merging.to_param}, valid_session
      assigns(:unit_template_merging).should eq(unit_template_merging)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UnitTemplateMerging" do
        expect {
          post :create, {:unit_template_merging => valid_attributes}, valid_session
        }.to change(UnitTemplateMerging, :count).by(1)
      end

      it "assigns a newly created unit_template_merging as @unit_template_merging" do
        post :create, {:unit_template_merging => valid_attributes}, valid_session
        assigns(:unit_template_merging).should be_a(UnitTemplateMerging)
        assigns(:unit_template_merging).should be_persisted
      end

      it "redirects to the created unit_template_merging" do
        post :create, {:unit_template_merging => valid_attributes}, valid_session
        response.should redirect_to(UnitTemplateMerging.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved unit_template_merging as @unit_template_merging" do
        # Trigger the behavior that occurs when invalid params are submitted
        UnitTemplateMerging.any_instance.stub(:save).and_return(false)
        post :create, {:unit_template_merging => {  }}, valid_session
        assigns(:unit_template_merging).should be_a_new(UnitTemplateMerging)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UnitTemplateMerging.any_instance.stub(:save).and_return(false)
        post :create, {:unit_template_merging => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested unit_template_merging" do
        unit_template_merging = UnitTemplateMerging.create! valid_attributes
        # Assuming there are no other unit_template_mergings in the database, this
        # specifies that the UnitTemplateMerging created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UnitTemplateMerging.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => unit_template_merging.to_param, :unit_template_merging => { "these" => "params" }}, valid_session
      end

      it "assigns the requested unit_template_merging as @unit_template_merging" do
        unit_template_merging = UnitTemplateMerging.create! valid_attributes
        put :update, {:id => unit_template_merging.to_param, :unit_template_merging => valid_attributes}, valid_session
        assigns(:unit_template_merging).should eq(unit_template_merging)
      end

      it "redirects to the unit_template_merging" do
        unit_template_merging = UnitTemplateMerging.create! valid_attributes
        put :update, {:id => unit_template_merging.to_param, :unit_template_merging => valid_attributes}, valid_session
        response.should redirect_to(unit_template_merging)
      end
    end

    describe "with invalid params" do
      it "assigns the unit_template_merging as @unit_template_merging" do
        unit_template_merging = UnitTemplateMerging.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UnitTemplateMerging.any_instance.stub(:save).and_return(false)
        put :update, {:id => unit_template_merging.to_param, :unit_template_merging => {  }}, valid_session
        assigns(:unit_template_merging).should eq(unit_template_merging)
      end

      it "re-renders the 'edit' template" do
        unit_template_merging = UnitTemplateMerging.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UnitTemplateMerging.any_instance.stub(:save).and_return(false)
        put :update, {:id => unit_template_merging.to_param, :unit_template_merging => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested unit_template_merging" do
      unit_template_merging = UnitTemplateMerging.create! valid_attributes
      expect {
        delete :destroy, {:id => unit_template_merging.to_param}, valid_session
      }.to change(UnitTemplateMerging, :count).by(-1)
    end

    it "redirects to the unit_template_mergings list" do
      unit_template_merging = UnitTemplateMerging.create! valid_attributes
      delete :destroy, {:id => unit_template_merging.to_param}, valid_session
      response.should redirect_to(unit_template_mergings_url)
    end
  end

end
